apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: store-canary-pr-{{ number }}
  namespace: apps  # stable namespace where apex service lives
spec:
  parentRefs:
    - kind: Service
      name: store        # apex ClusterIP used by callers
  rules:
    - matches:
        - headers:
            - name: X-Canary
              value: "{{ number }}"
      backendRefs:
        - name: store-service-pr-{{ number }}
          namespace: apps  # canary service in same namespace
          port: 80
    - backendRefs:
        - name: store-service
          namespace: apps  # stable namespace
          port: 80
