apiVersion: v1
kind: Service
metadata:
  name: store-service
  labels:
    app: store-service
spec:
  selector:
    app: store-service
  ports:
    - port: 80
      targetPort: 8080
      name: grpc
    - port: 9090
      targetPort: 9090
      name: metrics
