apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingressroute.yaml
images:
  - name: ghcr.io/rinsecrm/api-service
    newTag: v1.0.0   # promotion bumps this
