apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: api-edge-pr-routers
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: your-org
          repo: api-service
          tokenRef: { secretName: github-token, key: token }
        requeueAfterSeconds: 120
  template:
    metadata:
      name: api-canary-router-pr-{{ number }}
      labels: { role: canary, pr: "{{ number }}", layer: edge }
    spec:
      project: canary-deployments
      destination:
        server: https://kubernetes.default.svc
        namespace: platform
      source:
        repoURL: https://github.com/your-org/api-service.git
        targetRevision: "{{ head_sha }}"
        path: deploy/edge
        kustomize:
          patches:
            - target: { apiVersion: traefik.containo.us/v1alpha1, kind: IngressRoute, name: api-canary-pr-PLACEHOLDER }
              patch: |-
                - op: replace
                  path: /metadata/name
                  value: api-canary-pr-{{ number }}
                - op: replace
                  path: /spec/routes/0/match
                  value: "Host(`api.dev.example.com`) && PathPrefix(`/`) && Headers(`X-Canary`, `{{ number }}`)"
                - op: replace
                  path: /spec/routes/0/services/0/namespace
                  value: api-canary-pr-{{ number }}
      syncPolicy:
        automated: { prune: true, selfHeal: true }
